Install matplotlib from their github master by pip
I could not use https://github.com/thouis/matplotlib/tarball/v1.0.1-notkagg
because it gave me the error
    src/ft2font.h:14:10: fatal error: 'ft2build.h' file not found
on both Mac OS X 10.6 and Mac OS X 10.7. I also could not simply do
pip install matplotlib because the released version did not work with
clang, which replaces llvm in Mac OS X 10.7
(see https://trac.macports.org/ticket/31046).

This commit has only been tested on Mac OS X 10.7.